import type { Metadata } from "next";
import { Audiowide } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/widgets/navigation";

const geistSans = Audiowide({
  subsets: ["latin"],
  weight: "400",
});
const geistMono = Audiowide({
  subsets: ["latin"],
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.className}`}>
        <Navigation language="en" />
        {children}
      </body>
    </html>
  );
}
